<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video About Us</name>
   <tag></tag>
   <elementGuidId>3f723cf3-2c3c-4c4a-af39-a99a16d97766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='example-video_html5_api']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#example-video_html5_api</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>1da6a0b1-e4be-4d56-a605-3520ec28bc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>imgs/front.jpg</value>
      <webElementGuid>406cd83c-24c4-49ce-9042-40f6d74ac06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>example-video_html5_api</value>
      <webElementGuid>52dabcb0-5a0c-46bd-b018-153b08ce3725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>26449fb9-8edf-42e4-90a5-d257fe9f09ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>84cf82fb-0724-490d-9d7d-61741a0cc5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://demoblaze.com/64794b57-d02b-4daf-9137-e40f0c4a9b20</value>
      <webElementGuid>d6c66de1-bc7b-4c7b-ac12-6105019c8f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example-video_html5_api&quot;)</value>
      <webElementGuid>ace8e962-c547-410f-a1d5-ffcf48cb79d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='example-video_html5_api']</value>
      <webElementGuid>3ce81358-5535-4f28-a370-5ec70165c471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='example-video']/video</value>
      <webElementGuid>6f7eb1d1-b580-43c5-bef8-562eed041bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[1]/following::video[1]</value>
      <webElementGuid>d4110765-18ad-4e93-94b6-2f45b8cfffb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[2]/following::video[1]</value>
      <webElementGuid>6462f73e-a8b2-4e46-9fae-7f1472097e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Player is loading.'])[1]/preceding::video[1]</value>
      <webElementGuid>2dd24584-57a3-47d4-b435-fa2d6056127b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play Video'])[1]/preceding::video[1]</value>
      <webElementGuid>8f53984e-93e4-4629-ace0-3e1111a06f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>a259959f-e5a4-486c-8a6c-9a2dd9fed023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'example-video_html5_api' and @src = 'blob:https://demoblaze.com/64794b57-d02b-4daf-9137-e40f0c4a9b20']</value>
      <webElementGuid>c5f73355-f9a5-414d-9630-745aa83aaa69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
