<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ae9cb674-bd70-423e-ac0a-c56f29f5a404</testSuiteGuid>
   <testCaseLink>
      <guid>b9498d53-f8c7-4616-9424-25b6c526cb37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Register, Login and Logout/Login and Logout - Data Driven Test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7ff64372-496f-4bbe-8dd7-d7d5f03966ac</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dataset Username and Password</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>665cca48-5031-4f17-9be0-0f8b1e7143ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad127709-4946-45ae-9e98-ff087341c612</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ff64372-496f-4bbe-8dd7-d7d5f03966ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>cd1e0bef-150b-431d-8c2d-8897431f7c67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ff64372-496f-4bbe-8dd7-d7d5f03966ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5b8715fe-3511-4136-be66-a479050e7a01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6e6a313-24a6-44ac-a5c1-0e5b5a87b73f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Register, Login and Logout/Invalid Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>622cd863-f726-4b50-beaf-d0c3d6c095f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9049bb4b-d359-4659-b598-eb866d13683a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6c62e2c-e047-450a-8b79-046b778e8ccc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e22ae32-b14c-405d-add2-a1ff045b60cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Register, Login and Logout/Login and Logout - Static</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4a7a577-0078-4aa4-802e-edac1c858a5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58109b44-f0f0-4953-8df1-71d96a7ff916</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f8a9266-64bb-4183-935c-60b25aa4a04d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
