<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Username - Signup</name>
   <tag></tag>
   <elementGuidId>024487e8-ee68-4395-854e-2a1a520ceb6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a96e84fe-7ad4-4c68-aada-4dc912e3134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1db5bcc3-0545-4f21-adf9-cd173208759e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd330e4c-4608-4561-a213-4b4bb133e144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-username</value>
      <webElementGuid>1738e771-bc27-4d75-8453-56c0ba4cf171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-username&quot;)</value>
      <webElementGuid>a10533f2-8b95-4931-a95a-ee417fa6fe50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign-username']</value>
      <webElementGuid>0034b34f-e351-4945-a3bd-8ecfe42a2a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>ccca5380-d188-44b3-b991-7ed3c868fe38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/form/div/input</value>
      <webElementGuid>08d1e10c-7858-4b98-9e8a-a1437c2460dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sign-username']</value>
      <webElementGuid>62643d60-444f-410f-a70c-b4316b3516e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
